FROM ruby:2.6.5

RUN gem source -r https://rubygems.org/ -a https://gems.ruby-china.com/ \
    && gem install rails -v '5.2.3' --no-document

# mysql-dev mysql-client => can not install in debian
#  mariadb-server

#  mariadb-dev => error
#  mariadb-client

# libmariadbd-dev
# libmariadbclient-dev



# mysql-client libmysqlclient-dev
# mariadb-server mariadb-client libmariadbclient-dev
