version: "3.3"

services:
  postgres:
    image: "postgres:11-alpine"
    container_name: postgres
    restart: always
    # network_mode: "host"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5442:5432"

volumes:
  postgres_data:
