version: "3.4"

services:
  redis:
    image: redis
    container_name: redis
    # network_mode: 'host'
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
